### ISSUE TITLE
transform in-line fields

### ISSUE THREAD

**Issue by estherk0** [openinfradev/kustomize-helm-transformer#8]
# Description
- Parse in-line fields
```
apiVersion: someteam.example.com/v1
kind: HelmValuesTransformer
metadata:
  name: site
spec:
  - chart_name: glance
    values:
      images.tags.bootstrap: $(global.docker_registry)/..../   
```

- Transfrom in-line fields to values defined in HelmValuesTransformer
